### ISSUE TITLE
compile failure with ocaml4.00

### ISSUE THREAD

**Issue by mk270** [samoht/dyntype#1]
opam install dyntype fails if your system compiler is ocaml 4.00; ocaml switch 3.12.1 made this problem go away for me.

See https://gist.github.com/3258619 for a log of a compile attempt. Error was:

Error: File lib/type.cmx
was not compiled with the `-for-pack Dyntype.Dyntype' option

**Comment by avsm** [comment]
fixed in dyntype-0.8.3, and opam updated
