### ISSUE TITLE
doesn't build against fresh type_conv

### ISSUE THREAD

**Issue by ygrek** [samoht/dyntype#3]
File "pa_lib/pa_value.ml", line 26, characters 29-109:
Error: This function expects too many arguments, it should have type
Camlp4.PreCast.Ast.ctyp -> Camlp4.PreCast.Ast.str_item

```
diff --git a/pa_lib/pa_type.ml b/pa_lib/pa_type.ml
index d83076e..bad8219 100644
--- a/pa_lib/pa_type.ml
+++ b/pa_lib/pa_type.ml
@@ -24,7 +24,7 @@ open Pa_type_conv

 let _ =
   add_generator "type_of"
-    (fun _ tds ->
+    (fun tds ->
       let _loc = loc_of_ctyp tds in
        <:str_item<
            $P4_type.gen tds$;
diff --git a/pa_lib/pa_value.ml b/pa_lib/pa_value.ml
index 1ca87b9..b2e3414 100644
--- a/pa_lib/pa_value.ml
+++ b/pa_lib/pa_value.ml
@@ -23,6 +23,6 @@ open Ast
 open Pa_type_conv

 let _ =
-  add_generator "value" (fun _ tds ->
+  add_generator "value" (fun tds ->
     let _loc = loc_of_ctyp tds in
     <:str_item< $P4_value.gen tds$ >>)
```

**Comment by avsm** [comment]
Dyntype-0.9.0+ requires the latest type-conv (108.07.00+)

You can downgrade to dyntype-0.8.5 if you have the older type-conv (108.00.02 or below).

(OPAM has these constraints already in the dyntype package, so please open a bug there if its not working for some reason)

**Comment by ygrek** [comment]
Hm! I was compiling the master branch of dyntype against the latest hg revision of type-conv.

**Comment by avsm** [comment]
Alas, the Bitbucket versions of Core lag behind the official released versions in the tarballs. This is something separate that we will fix in the next month, but for now use the released tarballs of Core.
